# These type hints match the ones in polars_io_tools.io_sources.dnf_visitor
# but they are not imported here to fully separate the polars_utils code
# from the general utils tests.
# These helper functions will be useful for testing
# the DNF expressions generated by the DNFVisitor
# for TickStore integrations, which will not be in the polars_utils module.
from datetime import date, datetime, timedelta
from typing import Any, List, Optional, Tuple

import numpy as np
import polars as pl
import pytest

# Import the testing utilities for filter pushdown analysis
from polars_io_tools.testing import (
    PredicateAnalyzer,
    PredicateTracker,
    io_source_assert,
)

# Re-export for convenient imports in tests
__all__ = (
    "PredicateTracker",
    "PredicateAnalyzer",
    "create_sample_data",
    "tester",
    "assert_dnf_equal",
    "io_source_assert",
)


def create_sample_data() -> pl.DataFrame:
    """Create a sample dataframe with various data types for testing predicate pushdown."""
    # Generate date range
    dates = [date(2023, 1, 1) + timedelta(days=i) for i in range(10)]
    datetimes = [datetime(2023, 1, 1, 12, 0, 0) + timedelta(hours=i) for i in range(10)]

    # Create the sample dataframe with multiple data types
    df = pl.DataFrame(
        {
            # Numeric types
            "id": list(range(1, 11)),
            "float_val": np.linspace(0.5, 5.0, 10),
            "int_val": [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
            # String types
            "string_val": ["A", "B", "C", "A", "B", "C", "D", "E", "A", "F"],
            "long_string": ["text_" + str(i) * 5 for i in range(10)],
            # Temporal types
            "date_val": dates,
            "datetime_val": datetimes,
            # Boolean
            "bool_val": [i % 2 == 0 for i in range(10)],
            "struct": [{"name": f"num_{i}", "value": i} for i in range(10)],
            # Null values mixed in
            "nullable": [i if i % 3 != 0 else None for i in range(10)],
        }
    )

    # Add a categorical column
    df = df.with_columns(pl.col("string_val").cast(pl.Categorical).alias("cat_val"))

    return df


@pytest.fixture
def tester():
    """Create a fresh PredicateTracker for each test with sample data."""
    return PredicateTracker(create_sample_data())


def assert_dnf_equal(result: Optional[List[List[Tuple[str, str, Any]]]], expected: Optional[List[List[Tuple[str, str, Any]]]], msg: str = None):
    """
    Assert that two DNF expressions are equivalent regardless of predicate order.
    This ignores ordering within each clause (inner list) but preserves clause order.
    """
    if result is None and expected is None:
        return True

    if result is None or expected is None:
        pytest.fail(f"One result is None but the other is not: result={result}, expected={expected}")

    # Convert each clause to a comparable representation
    result_clauses = [sort_clause(clause) for clause in result]
    expected_clauses = [sort_clause(clause) for clause in expected]

    # Check that each clause in result appears in expected
    missing_in_expected = [clause for clause in result_clauses if not clause_in_list(clause, expected_clauses)]
    # Check that each clause in expected appears in result
    missing_in_result = [clause for clause in expected_clauses if not clause_in_list(clause, result_clauses)]

    if missing_in_expected or missing_in_result:
        error_msg = "\nDNF structures don't match!"
        if missing_in_expected:
            error_msg += f"\nOnly in result: {missing_in_expected}"
        if missing_in_result:
            error_msg += f"\nOnly in expected: {missing_in_result}"

        if msg:
            error_msg += f"\n{msg}"

        pytest.fail(error_msg)


def sort_clause(clause: List[Tuple[str, str, Any]]) -> List[Tuple[str, str, Any]]:
    """
    Sort a clause by its column names and operators for consistent comparison.
    Since we can't hash the entire tuple if some values are unhashable,
    we'll sort by the first two elements (column and operator).
    """
    return sorted(clause, key=lambda x: (x[0], x[1]))


def clause_in_list(clause: List[Tuple[str, str, Any]], clause_list: List[List[Tuple[str, str, Any]]]) -> bool:
    """
    Check if a clause appears in a list of clauses, with deep comparison for values.
    """
    for other_clause in clause_list:
        if len(clause) != len(other_clause):
            continue

        # Check if all tuples in clause match with tuples in other_clause
        if all(tuples_equal(a, b) for a, b in zip(clause, other_clause)):
            return True

    return False


def tuples_equal(a: Tuple[str, str, Any], b: Tuple[str, str, Any]) -> bool:
    """
    Compare two predicate tuples, handling special cases for collections and None values.
    """
    if a[0] != b[0] or a[1] != b[1]:  # Column and operator must match exactly
        return False

    # Handle None values
    if a[2] is None and b[2] is None:
        return True

    # Handle collection types (list, tuple, etc.)
    if isinstance(a[2], (list, tuple)) and isinstance(b[2], (list, tuple)):
        if len(a[2]) != len(b[2]):
            return False
        return all(x == y for x, y in zip(a[2], b[2]))

    # For all other types, use regular equality
    return a[2] == b[2]
