import datetime
from unittest.mock import patch

import polars as pl
import pytest
from polars.exceptions import ComputeError
from polars.testing import assert_frame_equal

import polars_io_tools as cpl

DUMMY_API_KEY = "dummy_api_key_for_testing"
DUMMY_APP_KEY = "dummy_app_key_for_testing"


@pytest.fixture
def mock_metric_query():
    """Fixture to mock the metric_query function."""
    with patch("polars_io_tools.io_sources.lazy_datadog_reader.metric_query") as mock:
        yield mock


def test_basic(mock_metric_query):
    """Test basic scan_datadog call with a simple mock response."""
    query = "avg:my.metric{tag:value} by {user}"

    # We need to massage the timestamps to match the expected format in the mock response.
    start_dt = datetime.datetime.fromtimestamp(1748635900000 // 1000, tz=datetime.timezone.utc).replace(tzinfo=None)
    end_dt = datetime.datetime.fromtimestamp(1748635960000 // 1000, tz=datetime.timezone.utc).replace(tzinfo=None)

    # The following mock response is a subset of an actual response
    # generated by the Datadog API for the given query.
    mock_response = {
        "status": "ok",
        "res_type": "time_series",
        "resp_version": 1,
        "query": "sum:piot_telemetry.test{type:call} by {user,module,function}.as_count()",
        "from_date": 1748635900000,
        "to_date": 1748635960000,
        "series": [
            {
                "unit": None,
                "query_index": 0,
                "aggr": "sum",
                "metric": "piot_telemetry.test",
                "tag_set": ["function:reutersadapter._init", "module:csp_internal.adapters.reuters", "user:svchfalgodev"],
                "expression": "sum:piot_telemetry.test{function:reutersadapter._init,module:csp_internal.adapters.reuters,user:svchfalgodev,type:call}.as_count()",
                "scope": "function:reutersadapter._init,module:csp_internal.adapters.reuters,type:call,user:svchfalgodev",
                "interval": 1,
                "length": 5,
                "start": 1748635902000,
                "end": 1748635940000,
                "pointlist": [
                    [1748635902000.0, 1.0],
                    [1748635914000.0, None],
                    [1748635915000.0, None],
                    [1748635937000.0, None],
                    [1748635940000.0, None],
                ],
                "display_name": "piot_telemetry.test",
                "attributes": {},
            },
            {
                "unit": None,
                "query_index": 0,
                "aggr": "sum",
                "metric": "piot_telemetry.test",
                "tag_set": ["function:dags", "module:cubist_sdlc.cli.dags", "user:cl8999"],
                "expression": "sum:piot_telemetry.test{function:dags,module:cubist_sdlc.cli.dags,user:cl8999,type:call}.as_count()",
                "scope": "function:dags,module:cubist_sdlc.cli.dags,type:call,user:cl8999",
                "interval": 1,
                "length": 5,
                "start": 1748635902000,
                "end": 1748635940000,
                "pointlist": [
                    [1748635902000.0, None],
                    [1748635914000.0, None],
                    [1748635915000.0, None],
                    [1748635937000.0, 1.0],
                    [1748635940000.0, None],
                ],
                "display_name": "piot_telemetry.test",
                "attributes": {},
            },
        ],
        "values": [],
        "times": [],
        "message": "",
        "group_by": ["function", "module", "user"],
    }
    mock_metric_query.return_value = mock_response

    lf = cpl.scan_datadog(query=query, api_key=DUMMY_API_KEY, app_key=DUMMY_APP_KEY).filter(
        (pl.col("timestamp") >= start_dt) & (pl.col("timestamp") < end_dt)
    )
    df = lf.collect()
    assert not df.is_empty()
    mock_metric_query.assert_called_once()

    # Another check, where we select specific columns (besides timestamp and value)
    second_df = (
        cpl.scan_datadog(query=query, api_key=DUMMY_API_KEY, app_key=DUMMY_APP_KEY)
        .filter((pl.col("timestamp") >= start_dt) & (pl.col("timestamp") < end_dt))
        .select(["user", "module", "function"])
    )
    second_df = second_df.collect()
    assert second_df.shape == (2, 3)


def test_no_lower_bound(mock_metric_query):
    """Test that we raise if no lower time bound is provided."""
    query = "a:query"
    with pytest.raises(ComputeError):
        cpl.scan_datadog(query=query, api_key=DUMMY_API_KEY, app_key=DUMMY_APP_KEY).filter(
            pl.col("timestamp") < datetime.datetime(2025, 1, 1)
        ).collect()
    mock_metric_query.assert_not_called()

    with pytest.raises(ComputeError):
        cpl.scan_datadog(query=query, api_key=DUMMY_API_KEY, app_key=DUMMY_APP_KEY).collect()
    mock_metric_query.assert_not_called()


def test_start_after_end(mock_metric_query):
    """Test that we raise if start time is after end time."""
    query = "a:query"
    start_dt = datetime.datetime(2023, 1, 2, tzinfo=datetime.timezone.utc)
    end_dt = datetime.datetime(2023, 1, 1, tzinfo=datetime.timezone.utc)

    df = (
        cpl.scan_datadog(query=query, api_key=DUMMY_API_KEY, app_key=DUMMY_APP_KEY)
        .filter((pl.col("timestamp") >= start_dt) & (pl.col("timestamp") < end_dt))
        .collect()
    )
    assert df.is_empty()

    second_df = (
        cpl.scan_datadog(query=query, api_key=DUMMY_API_KEY, app_key=DUMMY_APP_KEY)
        .filter((pl.col("timestamp") >= start_dt) & (pl.col("timestamp") < end_dt))
        .select(["timestamp", "value"])
        .collect()
    )
    assert second_df.is_empty()
    assert second_df.shape == (0, 2)

    mock_metric_query.assert_not_called()


def test_empty_response(mock_metric_query):
    """Test handling of an empty API response."""
    query = "an:empty {query}"
    start_dt = datetime.datetime(2023, 1, 1, tzinfo=datetime.timezone.utc)
    end_dt = datetime.datetime(2023, 1, 2, tzinfo=datetime.timezone.utc)

    mock_metric_query.return_value = {"series": []}
    lf = cpl.scan_datadog(query=query, api_key=DUMMY_API_KEY, app_key=DUMMY_APP_KEY).filter(
        (pl.col("timestamp") >= start_dt) & (pl.col("timestamp") < end_dt)
    )
    df = lf.collect()

    assert df.is_empty()
    mock_metric_query.assert_called_once()


def test_interval_parameter(mock_metric_query):
    """Test that the dd_interval parameter is passed to metric_query."""
    query = "some:query"
    custom_interval = 300
    start_dt = datetime.datetime(2023, 1, 1)
    end_dt = datetime.datetime(2023, 1, 2)

    mock_metric_query.return_value = {"series": []}

    lf = cpl.scan_datadog(query=query, api_key=DUMMY_API_KEY, app_key=DUMMY_APP_KEY, dd_interval=custom_interval).filter(
        (pl.col("timestamp") >= start_dt) & (pl.col("timestamp") < end_dt)
    )
    lf.collect()

    mock_metric_query.assert_called_once_with(
        query=query,
        start=int(start_dt.timestamp()),
        end=int(end_dt.timestamp()),
        api_key=DUMMY_API_KEY,
        app_key=DUMMY_APP_KEY,
        interval=custom_interval,
    )


def test_chunking(mock_metric_query):
    """Test that API calls are chunked based on max_chunk_duration_seconds."""
    query = "my.chunked.metric"
    # 2 hours range, 1 hour chunk duration -> 2 calls
    start_dt = datetime.datetime(2023, 1, 1, 0, 0, 0, tzinfo=datetime.timezone.utc)
    end_dt = datetime.datetime(2023, 1, 1, 2, 0, 0, tzinfo=datetime.timezone.utc)
    max_chunk_sec = 3600

    mock_response_chunk = {
        "series": [
            {"metric": "my.chunked.metric", "pointlist": [[start_dt.timestamp() * 1000 + i * 1000, float(i)] for i in range(2)], "tag_set": []}
        ]
    }
    mock_metric_query.return_value = mock_response_chunk

    lf = cpl.scan_datadog(query=query, api_key=DUMMY_API_KEY, app_key=DUMMY_APP_KEY, max_chunk_duration_seconds=max_chunk_sec).filter(
        (pl.col("timestamp") >= start_dt.replace(tzinfo=None)) & (pl.col("timestamp") < end_dt.replace(tzinfo=None))
    )
    df = lf.collect()

    assert mock_metric_query.call_count == 2
    assert len(df) == 4


# These tests verify that scan_datadog LazyFrames can be serialized with cloudpickle,
# which is required for distributed computing (e.g., Ray). Tests are located here
# rather than in test_pickle.py because they require Datadog API mocking infrastructure.


class TestScanDatadogPickle:
    """Tests for scan_datadog cloudpickle serialization support."""

    def test_scan_datadog_pickle_basic(self, mock_metric_query):
        """scan_datadog LazyFrames can be pickled and unpickled."""
        import cloudpickle

        query = "avg:my.metric{tag:value}"
        start_dt = datetime.datetime(2023, 1, 1, 0, 0, 0)
        end_dt = datetime.datetime(2023, 1, 1, 1, 0, 0)

        mock_response = {
            "series": [
                {
                    "metric": "my.metric",
                    "pointlist": [[start_dt.timestamp() * 1000, 1.0], [(start_dt.timestamp() + 1800) * 1000, 2.0]],
                    "tag_set": ["tag:value"],
                }
            ]
        }
        mock_metric_query.return_value = mock_response

        lf = cpl.scan_datadog(query=query, api_key=DUMMY_API_KEY, app_key=DUMMY_APP_KEY).filter(
            (pl.col("timestamp") >= start_dt) & (pl.col("timestamp") < end_dt)
        )

        # Pickle roundtrip
        pickled = cloudpickle.dumps(lf)
        lf_unpickled = cloudpickle.loads(pickled)

        # Verify schema is preserved
        assert lf.collect_schema() == lf_unpickled.collect_schema()

        # Verify data matches (both collected within mock context)
        expected = lf.sort("timestamp").collect()
        result = lf_unpickled.sort("timestamp").collect()
        assert_frame_equal(expected, result)

    def test_scan_datadog_pickle_with_filter(self, mock_metric_query):
        """scan_datadog with filters can be pickled."""
        import cloudpickle

        query = "avg:my.metric{tag:value}"
        start_dt = datetime.datetime(2023, 1, 1, 0, 0, 0)
        end_dt = datetime.datetime(2023, 1, 1, 1, 0, 0)

        mock_response = {
            "series": [
                {
                    "metric": "my.metric",
                    "pointlist": [
                        [start_dt.timestamp() * 1000, 1.0],
                        [(start_dt.timestamp() + 1800) * 1000, 5.0],
                    ],
                    "tag_set": ["tag:value"],
                }
            ]
        }
        mock_metric_query.return_value = mock_response

        lf = (
            cpl.scan_datadog(query=query, api_key=DUMMY_API_KEY, app_key=DUMMY_APP_KEY)
            .filter((pl.col("timestamp") >= start_dt) & (pl.col("timestamp") < end_dt))
            .filter(pl.col("value") > 3.0)
        )

        pickled = cloudpickle.dumps(lf)
        lf_unpickled = cloudpickle.loads(pickled)

        # Verify schema is preserved
        assert lf.collect_schema() == lf_unpickled.collect_schema()

        # Verify data matches
        expected = lf.sort("timestamp").collect()
        result = lf_unpickled.sort("timestamp").collect()
        assert_frame_equal(expected, result)
